#!/usr/bin/env python3
"""Expand the gateway's wildcard model entry into the models your key can reach.

    ./scripts/render-litellm-config.py          # writes litellm/config.generated.yaml

litellm/config.yaml carries a `model_name: "*"` entry, which routes correctly but
makes LiteLLM advertise its entire built-in catalogue -- hundreds of models, most
of which your project cannot call. LibreChat populates its picker from that list,
so attendees would scroll past image and audio models to find the two or three
that work.

This asks the provider what the key can actually reach (`GET /v1/models` returns
exactly the project's allowlist) and writes one entry per model. No model names
are stored in the repo: the list is discovered every time the stack starts.

If the provider cannot be reached, the wildcard config is used unchanged -- a
noisy picker beats a stack that will not start.
"""

import json
import os
import pathlib
import re
import sys
import urllib.error
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "litellm" / "config.yaml"
OUT = ROOT / "litellm" / "config.generated.yaml"
ENV = ROOT / ".env"
API_BASE = os.environ.get("LLM_API_BASE", "https://api.openai.com/v1")


def read_env_literally(path):
    """Parse .env as data, never as shell.

    Mirrors load_env() in scripts/llm-check.sh: a value containing $(...) is a
    string, not a command. Same normalisation (CRLF, BOM, quotes, inline
    comments) so the two cannot disagree about what the file says.
    """
    out = {}
    if not path.is_file():
        return out
    for i, raw in enumerate(path.read_text(errors="replace").splitlines()):
        line = raw.lstrip("﻿" if i == 0 else "").strip()
        if not line or line.startswith("#"):
            continue
        line = line[len("export "):] if line.startswith("export ") else line
        if "=" not in line:
            continue
        name, _, value = line.partition("=")
        name, value = name.strip(), value.strip()
        if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", name):
            continue
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        else:
            m = re.match(r"^(.*[^\s])\s+#.*$", value)
            if m:
                value = m.group(1)
        if value:
            out[name] = value
    return out


def fetch_models(key):
    req = urllib.request.Request(
        f"{API_BASE}/models", headers={"Authorization": f"Bearer {key}"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return sorted(m["id"] for m in json.load(r).get("data", []))


def render(src_text, models):
    entries = ["".join(
        f"  - model_name: {m}\n"
        f"    litellm_params:\n"
        f"      model: openai/{m}\n"
        f"      api_key: os.environ/LLM_API_KEY\n") for m in models]
    wildcard = re.compile(
        r"""  - model_name: ["']\*["']\n(?:    .*\n|      .*\n)*?(?=\n|  - model_name:)""")
    if not wildcard.search(src_text):
        sys.exit("could not find the wildcard entry in litellm/config.yaml")
    banner = (f"  # Generated by scripts/render-litellm-config.py from the "
              f"{len(models)} model(s)\n  # your key can reach. Edit "
              f"litellm/config.yaml, not this file.\n")
    return wildcard.sub(banner + "".join(entries) + "\n", src_text, count=1)


def main():
    src = SRC.read_text()
    env = read_env_literally(ENV)
    key = os.environ.get("LLM_API_KEY") or env.get("LLM_API_KEY")
    if not key:
        print("no LLM_API_KEY in environment or .env - using the wildcard config "
              "(the model picker will be long).", file=sys.stderr)
        OUT.write_text(src)
        return 0
    try:
        models = fetch_models(key)
    except urllib.error.HTTPError as e:
        detail = e.read().decode(errors="replace")[:120]
        print(f"could not list models ({e.code}): {detail}", file=sys.stderr)
        print("using the wildcard config instead.", file=sys.stderr)
        OUT.write_text(src)
        return 0
    except Exception as e:
        print(f"could not reach {API_BASE}: {e}", file=sys.stderr)
        print("using the wildcard config instead.", file=sys.stderr)
        OUT.write_text(src)
        return 0
    if not models:
        print("the provider returned no models for this key - using the wildcard "
              "config.", file=sys.stderr)
        OUT.write_text(src)
        return 0
    OUT.write_text(render(src, models))
    print(f"wrote {OUT.relative_to(ROOT)} with {len(models)} model(s): "
          f"{', '.join(models)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
